"""new fields in user model

Revision ID: 951d89155451
Revises: 05ea41324ac1
Create Date: 2024-04-10 12:59:25.774078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951d89155451'
down_revision = '05ea41324ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
